### PR TITLE
Design update

### PR DESCRIPTION
**Pull request by StefanPeev**

### CODE REVIEW

**Comment by catharanthus** [comment]
Well, I finally looked through the proposed changes and there are some issues:

1. I don't agree with the Serbian/Macedonian versions of **г**, **д**, **п**, **т** in the oblique style. These are italic shapes, but Evolventa does not have the italic style, only oblique which should be a slanted version of the upright style. It does not make sense to have a typeface where only a few glyphs are italic, and others are oblique.

2. I still think that alternate **ц** and **щ** should use tails typical for Evolventa, like their "normal" counterparts.

3. Alternate **б** is also clearly a stylistic choice. I'm not sure it is necessary or have anything to do with localized Cyrillics.

4. Alternate **в** and **з** still look somewhat off in the regular style, and even worse in the bold style. I'm still not sure what we can do with them. Maybe make them narrower (especially **в**)?

5. Alternate **ъ**, **ы**, **ь** also don't look very good in bold. I feel that they are too "compressed" in vertical direction.

6. I don't think that the idea of disjointed **ж**, **к** and **я** works for the bold style. It could be better to leave them disjointed in the regular style, but not in bold, like in the ParaType's version of Avant Garde Gothic (https://www.paratype.ru/pstore/default.asp?fcode=PT_AVG&letter=A - the fonts are not free, but you can look at samples), or even in the Latin part (compare regular **R** with bold **R**).

While there are also kerning issues, I think it is too early to discuss them.

**Comment by StefanPeev** [comment]
Thank you, Alex! Well:
1. I haven't models for Serbian/Macedonians **г, д, п** in the oblique style. If you have, please show me and lets we make the local glyphs in Evolventa in this direction for those Cyrillic languages - I agree.
2. For the **ц** - please show me your idea about the tail and the glyphs in a Bulgarian Cyrillic variant.
3. Alternate **б** – уеs, it is a stylistic choice for Bulgarian because of the other Bulgarian glyphs like **в**. The default **б** is too bigger to be used in Bulgarian Cyrillic form. Don't you think so?
4. Alternate **в** and **з** – OK, I still think about them and I'm ready to change their design as far as I have a better one.
5. The bold variant as a hole needs redesign – I agree with you and I'll make changes.
6. I'll look at Avant Garde Gothic and I'll rethink the design. Thank you!
7. But what do you think about regular **м** and bold **м** in the default Cyrillic and of course in all other Cyrillic foms. Don't you think there is a need for a chage?

**Comment by catharanthus** [comment]
1. This is not exactly what I meant. Basically, "oblique" is really just a nice name for mechanically slanted upright glyphs, while "italic" is an entirely separate style. For example, look at Cyrillic (default) **и** and **т** in Evolventa Oblique (or, for that matter, Avant Garde Gothic Book Oblique). This is not how these letters are supposed to look in Italic in Russian (compare with Arial). Evolventa does not have an italic style, and the oblique style is supposed to be a slanted version of upright glyphs, be it Latin, Russian Cyrillic, Bulgarian Cyrillic or whatever. To put it another way, I suggest concentrating on regular and bold styles for now. Oblique and bold oblique are then produced more or less automatically.

7) Yes, I'm still not sure about that decision with bold Cyrillic **М**. The idea was to prevent that joint from looking too thick/heavy.

**Comment by StefanPeev** [comment]
1. Alex, I understand what you mean but the question is whether in this situation Serbian **п** in oblique will be just the traditional **п** glyph (slanted at 10,5 degree) with macron above. The same question is for the other Serbian Cyrillic oblique forms. Cursive Serbian Cyrillic **п** and oblique Serbian Cyrillic **п** have quite a different look. I really haven't seen Serbian oblique forms. OK, I'll try to find some Serbian oblique forms to be sure how Serbian people find a decision to our question.
2. Alex, Evolventa is your font and the final decisions must be yours. I just try to help you make Evolventa a font suitable for much more people. But I do suggest you to make the bold **м** in the same way as the regular one.

**Comment by StefanPeev** [comment]
Alex, on my question in [Local Fonts Group in FB](https://www.facebook.com/groups/844548739032283/) Igor Petrovic (Serbian designer and typograph) gave the next explanation:

> Igor Petrovic: Thanks for your trust! It's hard to be completely sure about this, I am not even sure there is some kind of official convention from university or something. But here is my personal thought:
> Seems that influence of traditional manual script on italics in Cyrillic is stronger than in Latin. Because of this Serbian italics "г", "д", "п", "т" have macron above, and Russian don't, because it's direct consequence of differences in manual script.
> On the other side, I think that it's up to designer to define how much manual script influence he want to put in italics.
> In other words I think that even in italics it's allowed to have just oblique forms of "г", "д", "п", "т" if you don't want much influence. But if you want influence, than it is important to make difference between Russian and Serbian, and put macron above in Serbian (if you decide to influence, than pick right influence).
> Oblique form is not so influenced by manual script, so I would say it's perfectly fine to have just slanted upright forms here. More than that, they are maybe more appropriate than "macron" versions in this case, because that way we keep clean logical difference between oblique/slanted and italics.

**Comment by StefanPeev** [comment]
macedonian_01
Macedonian, Bulgarian, Russian and Serbian Cyrillic (a table, made by Lasko Dzurovski – Macedonian typographer)

**Comment by StefanPeev** [comment]
evolventa_05

**Comment by StefanPeev** [comment]
And here is an example of Serbian Cyrillic Oblique (font Avangarda by ZORAN KOSTIĆ).
serbian_avangarda_cyrillic_oblique_01

**Comment by StefanPeev** [comment]
evolventa_cyrillic_05
evolventa_cyrillic_06
evolventa_cyrillic_07
evolventa_cyrillic_08

**Comment by StefanPeev** [comment]
evolventa_cyrillic_09
evolventa_cyrillic_10

**Comment by catharanthus** [comment]
So, apparently there is no shortage in Avant Garde clones, even with Cyrillic...

> Oblique form is not so influenced by manual script, so I would say it's perfectly fine to have just slanted upright forms here. More than that, they are maybe more appropriate than "macron" versions in this case, because that way we keep clean logical difference between oblique/slanted and italics.

Let's keep obliques as slanted upright shapes then.

Don't get me wrong, it's not like the idea of making "true" italics didn't cross my mind, but a considerable skill is needed to make decent italics, and I'm just not that good.

By the way, Evolventa-Bold.sfd (FontForge source) contains alternate **м** in the background layer. Do you think it is better?

**Comment by StefanPeev** [comment]
Thank you, Alex. As you see, I agree with you for the oblique forms :) . I'm just finishing the design and will send you a new PR with all styles. I hope it will be today – more latter. I'll check the new **м** also.

**Pull request closed without merging**
